### ISSUE TITLE
实时测试问题

### ISSUE THREAD

**Issue by shangchengPKU** [fengq1a0/FOF#1]
您出色的工作十分令我震撼，但是我有几个问题想要跟您学习一下：
1.您在论文里面提及到了实时问题，并且展示了相关的实时的视频demo，但是我自己对代码进行测试的时候需要的时间是10s左右，我所使用的服务器显卡是您在论文提到的型号，所以这里我不太理解，因为这样的话是属于先对图像进行了初步的建模，随后在调整的嘛，因为我看您的视频demo确实实时的；
2.您在视频里面的实时，是否可以对视频流进行处理呢？那样是否也可以做到实时呢？
谢谢您的宝贵时间

**Comment by fengq1a0** [comment]
## 实时性

实时应用涉及许多工程实现等细节问题。

1. 排除干扰

您说的10s左右，应该包含了模型加载、以及mesh写入磁盘等时间，这些都要排除在外。同时请确保gpu上没有运行其他程序。（事实上写入磁盘通常是最大的瓶颈）  

一个简单的测试方法是使用tqdm，通过 xxx its/s 可简单评估帧率。
```
# img is the tensor of the image on device
# model is a warp of network on device
for i in tqdm.tqdm(range(1000)):
    v, f = model(img)
```

当前给出的代码中，不包含gpu marching cube等代码。
上述简单评价帧率的代码将在本周日前更新。


2. pytorch优化

由于pytorch的立即执行模型，其性能也是极度受限的。
可以通过
```
torch.backends.cudnn.benchmark = True
torch.jit.trace
```
改善性能，加之gpu marching cube，此时已经能达到实时水平。
这些也将包含在周日的更新中。
此外使用tensorrt将进一步提升性能。

3. 进一步优化

python的性能非常有限。包括gpu marching cube、渲染等外围部分性能都不高。
因此要获得极致顺滑的结果，需要使用cpp+cuda进行实现。  



## 视频流

FOF可以对实时视频流进行处理。
但是请注意一个obj格式的人体mesh大概5MB。
30 its/s将是非常大的数据量。硬盘的容量及写入速度都无法支持。
所以只建议如demo video中一样，实时使用，而不保存mesh。
