### ISSUE TITLE
现在仓库的源码在使用时是必须要先生成smplx是吗

### ISSUE THREAD

**Issue by murphyl4** [fengq1a0/FOF#10]
我看在test时也是需要smplx的输入来推理法线

**Comment by fengq1a0** [comment]
是的，目前的code需要smpl/smplx模型做输入。

**Comment by murphyl4** [comment]
谢谢您的回复，我想问一下这样能保证实时性吗，您的团队有没有测试过

**Comment by fengq1a0** [comment]
是可以的，但是需要一些工程优化，可以看下面的主页。
https://cic.tju.edu.cn/faculty/likun/projects/FOFX/index.html

事实上这个code是我们这个工作的扩期刊的代码，马上就会挂arxiv

**Comment by murphyl4** [comment]
谢谢！这个方法真的很好，希望更多人看到
