### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by murphyl4** [fengq1a0/FOF#11]
你好，我在训练的时候有两个问题麻烦问您一下
1. 我使用THuman2.0数据集进行的训练，500个mesh256个视角4个light作为训练集，在训练了10个epoch后realworld测试结果特别差。下面的图分别是mesh正面和侧面视角。
![front](https://github.com/user-attachments/assets/545eccf4-2ea2-4fcd-8812-a0916472d5ce)
![side](https://github.com/user-attachments/assets/4da571e7-98e9-4a2b-8dbe-ff810599947b)
但是使用您提供的预训练权重得到的结果很不错
![front1](https://github.com/user-attachments/assets/237adeb9-ed9b-45e7-b026-75061f523dc4)
![side1](https://github.com/user-attachments/assets/4f14a728-8f08-4f9f-a9cf-b545640b8d55)
我想知道您有觉得有什么地方可能出问题吗？
另外在训练集的效果还不错
![image](https://github.com/user-attachments/assets/b6428553-f97f-4f2a-a2ac-ea1336161a7a)
测试集有的好有的坏
![image](https://github.com/user-attachments/assets/b9121d67-5790-4bef-a95e-3c2bc68b1c2e)
![image](https://github.com/user-attachments/assets/2c3c40af-371f-40a9-9a44-88b514a35cad)

2. 看到您论文里说可以很方便的生成各种分辨率的mesh，我如果想使用256分辨率的图片生成256*256*256的mesh我应该怎么做？

谢谢您

**Comment by murphyl4** [comment]
对了，我使用的原版的FOF，没有添加smpl和normal信息

**Comment by fengq1a0** [comment]
你好！抱歉回复有些迟。
我之前有check过这个问题，原因是原始release的code，对数据特别地敏感。非watertight，自体穿模的mesh都会导致求得的coefficients不稳定，导致训练数据不准确，会过拟合。

为了解决这个问题，我当时合并了离散的面片，处理了watertight的问题（你如果检查Thuman2.0的mesh，你会发现它们是分成了几个大部分，而不是连成的整体）

这里建议你使用新的训练code，使用新的code进行训练应该没有问题。新的训练code会在训练时，自己渲染normal和fof，并且对那些数据问题鲁棒。

**Comment by LLLLLLLianHua** [comment]
您好，我在训练时也遇到了相同的问题
请问您所说的合并离散面片的操作是已经发布在新的分支了嘛？
对数据处理再训练原版的FOF后，是否可以得到与您提供的模型相同的效果
谢谢您

**Comment by fengq1a0** [comment]
新的训练code会在训练时，实时cuda渲染normal和fof，保证了数据对齐，并且对那些数据问题鲁棒。而且这个版本数据处理流程比之前简短了，出现潜在问题的可能更小。所以请使用新branch的code，能稳定复现效果。

之前的版本，在合并共享顶点的面片之后，仍有10几个mesh存在问题。很难用一份代码通用解决，这部分mesh是手动修复的，所以有点难以提供。

**Comment by fengq1a0** [comment]
请看新branch的```preprocess.py``` line 63 和 line 81。
这两个操作可以解决大部分mesh问题，但是经过检查，有很少一部分mesh还是存在些许问题，但是不会特别影响训练了。

理论上不进行这个处理，新的fof计算方式也对这些数据鲁棒

**Comment by LLLLLLLianHua** [comment]
感谢您的回复
还有一个问题，我可以基于您提供的预训练权重生成分辨率是256的模型嘛？

**Comment by fengq1a0** [comment]
可以的，只需要对生成的fof像图像一样进行下采样即可，对降采样后的fof直接进行解码即可。
