### ISSUE TITLE
FOF_Normal和FOF

### ISSUE THREAD

**Issue by 1aq-qa1** [fengq1a0/FOF#12]
您好！感谢您很棒的工作！
我注意到在lib/fof/fof_utils.py中有两个类 FOF_Normal和FOF，请问他们的作用是什么呀？以及分别有什么区别呢？

**Comment by fengq1a0** [comment]
你好。它们的作用类似。

## step1 实例化
请查看train.py line: 73
首先实例化 这个类
```
fof_render = FOF_Normal(args["bs"],512).to(0)
```
参数分别是batchsize，分辨率，to cuda设备（传入“cuda:0”也没问题）

## step2 使用
然后可以看train.py line: 24，这是如何使用
```
fof_mesh, dF, dB, nF, nB = fof_render(vv, vn, 128)
```

输入是顶点坐标，顶点颜色，以及fof的系数数量。返回的是fof，正反面depth，正反面渲染。

顶点的shape是[B,N,3,3]  分别是 Batchsize，面片数量，每个面片三个顶点，每个顶点三维坐标。
顶点颜色的shape与顶点坐标一样，只不过不是三维坐标，而是RGB颜色。  

fof的计算过程包含了光栅化，所以这里顺便支持了渲染。在渲染法线时，只需要把输入的顶点颜色换成顶点法线即可。此时返回的正反面渲染就是正反面法线。

当你不需要这个额外的渲染功能时，随便传入一个这个shape的tensor即可，比如就是顶点坐标。

## 不同
FOF_Normal包含了给顶点颜色，顺便渲染的功能。FOF只能渲染fof，不能顺便渲染颜色。建议直接使用FOF_Normal即可。

## 好处
不用提前计算，存储fof和normal了。
一方面渲染normal有一点点麻烦，而且很费存储空间。
另一方面用这个code，出来的法线和fof肯定对应，避免了各种奇怪的问题导致的不对应，进而导致训练结果不对的情况。

**Comment by fengq1a0** [comment]
我有在考虑多写个文档，介绍下这两个类。目前来说在你的项目中使用fof是非常简单的。只需要copy一下lib/fof。然后在你的项目里快乐地实时渲染就好了。

**Comment by 1aq-qa1** [comment]
非常感谢您的详细解答！
顺便问一下，我注意到您的最新的工作：FOF-X: Towards Real-time Detailed Human Reconstruction from a Single Image非常棒的工作！非常期待您能够提供最新工作的代码！
