### ISSUE TITLE
Hello, can you provide me with the processed THuman2.0 dataset

### ISSUE THREAD

**Issue by hanchaoyuan** [fengq1a0/FOF#6]
I tried to process the THumans2.0 dataset myself, but when I ran this command  “python prt_util.py”, it took hours with no output, and I had no idea if something was wrong. Can you share the processed dataset if possible?

**Comment by fengq1a0** [comment]
Sorry, my PRT files have been deleted. They are about 4 times larger than the meshes so I had to do so.

Yes, it's very time consuming to run “python prt_util.py”. You need really good CPUs and large enough memory or it may crash (That's what happened to you). This script is borrowed from PIFu and I'm not going to fix or improve it..... Instead, I use a blender based script to render images now......

So I suggest you finding another renderer... My current script is full of bugs, so I won't share it.
