### ISSUE TITLE
When will the data structure and data process be uploaded?

### ISSUE THREAD

**Issue by LanguageDriven3DPoseEstimation** [fengq1a0/FOF#9]
First of all, thank you for your great work!
I found that you have uploaded a new code of FOF recently. But I don't know what is the data structure of THUman and how to process these data. I tried to figure out this by looking dataset_mesh_only.py, but I still don't know the data structure accurately.
Could you upload the data structure and data process?
Thanks!

**Comment by fengq1a0** [comment]
Thank you for your interest! I'll upload that as soon as possible. (tomorrow I think)

**Comment by fengq1a0** [comment]
Check the updated Data preprocess section in readme. If you have any questions, feel free to let me know.
